### PR TITLE
Merge pull request #1 from fpetillo/master

### PR DESCRIPTION
**Pull request by fpetillo**
Updated to compile with zero warnings and cleaned up a few things. Se…

### CODE REVIEW

**Comment by fpetillo** [comment]
latest pull request

**Comment by geneb** [comment]
As far as I can tell, no changes were made so I'm going to just close this pull request without merging.

**Comment by fpetillo** [comment]
Yes, my bad on the request.  Thanks Gene!

 

 

        Frank A. Petillo, Sr.
Owner, Acuityware LLC
609.489.6001 | 908.768.9260 | frank@acuityware.com
http://acuityware.com
105 Topside Rd. Manahawkin, NJ 08050

**Comment by geneb** [comment]
No worries Frank. :)  Currently the Release & Master branches are 32 bit-only.  If you want to play with the 64 bit stuff, grab dev.

g.

**Comment by fpetillo** [comment]
Yes, I will and looking forward to contributing.   This could be very exciting for a number of reasons.

 

Thank you for all your efforts thus far!

 

 

        Frank A. Petillo, Sr.
Owner, Acuityware LLC
609.489.6001 | 908.768.9260 | frank@acuityware.com
http://acuityware.com
105 Topside Rd. Manahawkin, NJ 08050

**Pull request closed without merging**
